### ISSUE TITLE
SMK Deployments to TEST/PROD

### ISSUE THREAD

**Issue by dhlevi** [bcgov/smk-legacy-ui#197]
Prepare to move SMK into test and production environments.

**Comment by ll911** [comment]
pls review https://sonarqube.data.gov.bc.ca/project/issues?id=ca.bc.gov.app%3Asmk-parent&resolved=false&types=BUG, if there are code from elsewhere, pls provide the exclusion list. https://docs.sonarqube.org/display/SONAR/Analysis+Parameters#AnalysisParameters-Exclusions/Inclusions

**Comment by dhlevi** [comment]
@ll911 Attempting to view the link just times out. We can clear up the issues, but we'll need to be able to see them first!

**Comment by dhlevi** [comment]
@ll911 Still unable to view the link in your comment above, with our without vpn running. If we can't access the link, can you at least send us a report of issues highlighted from sonar so we know what needs to be addressed?

**Comment by ll911** [comment]
@dhlevi did you get the new url in slack channel? deployment pattern follow https://github.com/kubernetes/examples/tree/master/staging/javaweb-tomcat-sidecar

**Comment by dhlevi** [comment]
@ll911 Yep, I was able to get the sonar data, and we've pushed up fixes to our forks for the reported issues. We'll be doing a merge and build likely by next week.

We'll take a look at the deployment pattern you've linked and get things ready for that!

**Comment by webgismd** [comment]
I think the creation for this issue was related to the task of getting the Admin UI TEST and PROD envs. The items in the previous comments are specific to the migration of the SMK Admin UI to those environments. I am not sure but I think this issue has been de-prioritized as the Admin UI will not proceed to those envs as planned. A backlog of Admin UI tasks is currently being tracked in this issue - https://github.com/bcgov/smk/issues/238. SMK Sites hosted by DataBC have an alternative pathway to TEST and PROD that is documented and separate from the Admin UI.

**Comment by cpspicer** [comment]
Agree - re purposing this task for ensuring we can migrate an SMK app (stand alone, fully baked app) through to our hosting area from the Github repo through to Openshift Prod.

**Comment by webgismd** [comment]
@cpspicer We gave documentation internally developed for the steps to deploy DataBC SMK Sites, (Which is a separate process from SMK code development that this repo documents.
